DROP TABLE IF EXISTS DAYS_RANGE;
DROP TABLE IF EXISTS AGE_RANGE;
DROP TABLE IF EXISTS DAYS_AGE_RANGE;

ALTER TABLE Czech DROP COLUMN DAYSD_20200101;
ALTER TABLE Czech DROP COLUMN DAYSVD1_20200101;
ALTER TABLE Czech DROP COLUMN AGE_2023;
COMMIT;
